px_git发生错误,时间：2020-02-14 21:32:49 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6ff7285a10>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=20)')):   
px_git发生错误,时间：2020-02-14 21:39:35 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5588cbc710>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=20)')):   
px_git发生错误,时间：2020-02-14 21:47:16 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcd985510d0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=20)')):   
px_git发生错误,时间：2020-02-14 21:52:21 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6fac130910>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=20)')):   
px_git发生错误,时间：2020-02-14 22:12:07 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by SSLError(SSLCertVerificationError("hostname 'raw.githubusercontent.com' doesn't match either of 'default.ssl.fastly.net', 'fastly.com', '*.a.ssl.fastly.net', '*.hosts.fastly.net', '*.global.ssl.fastly.net', '*.fastly.com', 'a.ssl.fastly.net', 'purge.fastly.net', 'mirrors.fastly.net', 'control.fastly.net', 'tools.fastly.net'"))):   
px_git发生错误,时间：2020-02-14 22:14:03 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by SSLError(SSLCertVerificationError("hostname 'raw.githubusercontent.com' doesn't match either of 'default.ssl.fastly.net', 'fastly.com', '*.a.ssl.fastly.net', '*.hosts.fastly.net', '*.global.ssl.fastly.net', '*.fastly.com', 'a.ssl.fastly.net', 'purge.fastly.net', 'mirrors.fastly.net', 'control.fastly.net', 'tools.fastly.net'"))):   
px_git发生错误,时间：2020-02-14 22:14:45 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by SSLError(SSLCertVerificationError("hostname 'raw.githubusercontent.com' doesn't match either of 'default.ssl.fastly.net', 'fastly.com', '*.a.ssl.fastly.net', '*.hosts.fastly.net', '*.global.ssl.fastly.net', '*.fastly.com', 'a.ssl.fastly.net', 'purge.fastly.net', 'mirrors.fastly.net', 'control.fastly.net', 'tools.fastly.net'"))):   
px_git发生错误,时间：2020-02-14 22:16:56 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by SSLError(SSLCertVerificationError("hostname 'raw.githubusercontent.com' doesn't match either of 'default.ssl.fastly.net', 'fastly.com', '*.a.ssl.fastly.net', '*.hosts.fastly.net', '*.global.ssl.fastly.net', '*.fastly.com', 'a.ssl.fastly.net', 'purge.fastly.net', 'mirrors.fastly.net', 'control.fastly.net', 'tools.fastly.net'"))):   
px_git发生错误,时间：2020-02-14 22:26:58 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by SSLError(SSLCertVerificationError("hostname 'raw.githubusercontent.com' doesn't match either of 'default.ssl.fastly.net', 'fastly.com', '*.a.ssl.fastly.net', '*.hosts.fastly.net', '*.global.ssl.fastly.net', '*.fastly.com', 'a.ssl.fastly.net', 'purge.fastly.net', 'mirrors.fastly.net', 'control.fastly.net', 'tools.fastly.net'"))):   
px_git发生错误,时间：2020-02-14 22:29:30 错误原因：HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /fate0/proxylist/master/proxy.list (Caused by SSLError(SSLCertVerificationError("hostname 'raw.githubusercontent.com' doesn't match either of 'default.ssl.fastly.net', 'fastly.com', '*.a.ssl.fastly.net', '*.hosts.fastly.net', '*.global.ssl.fastly.net', '*.fastly.com', 'a.ssl.fastly.net', 'purge.fastly.net', 'mirrors.fastly.net', 'control.fastly.net', 'tools.fastly.net'"))):   
px_git发生错误,时间：2020-02-14 22:33:29 错误原因：('Connection aborted.', OSError(0, 'Error')):   
